# Branch: Branch Cairo  — generated 2026-05-02 16:46
# Deploy this file as /etc/wireguard/wg0.conf on the branch router
[Interface]
Address    = 10.200.0.2/24
ListenPort = 51820
PrivateKey = F2gKByUtvCDbce59x2celvC0zTdVzzZIlzGsXXKSsqg=
DNS        = 192.168.0.10

# HQ peer
[Peer]
PublicKey  = JeNTP8l5NxpYSw6Qw1Hno3M8w2o8SCbIRuHaq32kQTc=
Endpoint   = 203.0.113.1:51820
AllowedIPs = 192.168.0.0/24, 10.200.0.0/24
PersistentKeepalive = 25
