# Branch: Branch Alexandria  — generated 2026-05-02 16:46
# Deploy this file as /etc/wireguard/wg0.conf on the branch router
[Interface]
Address    = 10.200.0.3/24
ListenPort = 51820
PrivateKey = XEo1mJer7IzOcW2eW9XyoCnZ2iO8bhbj5TgfxUO8WB4=
DNS        = 192.168.0.10

# HQ peer
[Peer]
PublicKey  = JeNTP8l5NxpYSw6Qw1Hno3M8w2o8SCbIRuHaq32kQTc=
Endpoint   = 203.0.113.1:51820
AllowedIPs = 192.168.0.0/24, 10.200.0.0/24
PersistentKeepalive = 25
