# HQ WireGuard Interface  — generated 2026-05-02 16:46
[Interface]
Address    = 10.200.0.1/24
ListenPort = 51820
PrivateKey = 4CUByH1D/2asWau58fKo6495elNLSG304WKev/bzzHg=
PostUp     = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown   = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# Peer: Branch Cairo
[Peer]
PublicKey  = xVzj2lKYBcIiseVu0cVNXGXgsAWdDca1+1GAFImnqN4=
AllowedIPs = 10.200.0.2/32, 192.168.1.0/24

# Peer: Branch Alexandria
[Peer]
PublicKey  = QbQ3223CL5ye6xYHNQbmgN46jHLsQTtl4rONm1lQcG4=
AllowedIPs = 10.200.0.3/32, 192.168.2.0/24

# Peer: Branch Luxor
[Peer]
PublicKey  = bEALAZam7wuDptn9+nceGrro/dMP1w+fTksuShxXCrE=
AllowedIPs = 10.200.0.4/32, 192.168.3.0/24
