# nftables ruleset for Branch Luxor
# Generated 2026-05-02 16:46

table inet filter {
    chain forward {
        type filter hook forward priority 0; policy drop;

        # Allow established / related
        ct state established,related accept

        # Approved services: branch LAN → HQ LAN
        ip saddr 192.168.3.0/24 ip daddr 192.168.0.0/24 tcp dport 80 accept comment "http"
        ip saddr 192.168.3.0/24 ip daddr 192.168.0.0/24 tcp dport 443 accept comment "https"
        ip saddr 192.168.3.0/24 ip daddr 192.168.0.0/24 udp dport 53 accept comment "dns"
        ip saddr 192.168.3.0/24 ip daddr 192.168.0.0/24 udp dport 123 accept comment "ntp"

        # Drop everything else from this branch
        ip saddr 192.168.3.0/24 drop
    }

    chain postrouting {
        type nat hook postrouting priority 100;
        ip saddr 10.200.0.0/24 oif eth0 masquerade
    }
}